# PyTorch tensors

- For today, the same as numpy arrays
    - But can run on a GPU

In [1]:
# Pytorch
import torch

In [2]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
a + b

tensor([5, 7, 9])

In [3]:
c = torch.stack([a,b])
(c, c.shape)

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [4]:
torch.cuda.is_available()

True

In [5]:
c.is_cuda

False

In [6]:
c_gpu = c.cuda()
(c_gpu, c.is_cuda)

(tensor([[1, 2, 3],
         [4, 5, 6]], device='cuda:0'),
 False)